name: 'Pip run'
description: 'Run tests'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  requirements:
    description: 'Requirements file name'
    default: 'requirements.txt'
    required: false
  command:
    description: 'Command to run'
    required: true
runs:
  using: "composite"
  steps:
  - id: preserve-envvars
    shell: bash
    run: echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> "$GITHUB_OUTPUT"
  - uses: actions/checkout@v4
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip
      cache-dependency-path: ${{ inputs.requirements }}
  - shell: bash
    if: steps.preserve-envvars.outputs.PKG_CONFIG_PATH
    run: echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${{ steps.preserve-envvars.outputs.PKG_CONFIG_PATH }}" >> "$GITHUB_ENV"
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r ${{ inputs.requirements }}
  - name: Run ${{ inputs.command }}
    shell: bash
    run:  ${{ inputs.command }}
