name: 'uv run'
description: 'Run tests'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  command:
    description: 'Command to run'
    required: true
  uv-install-options:
    description: "uv sync options"
    default: ""
  cache:
    description: "Cache python environment?"
    default: true
  env:
    description: 'JSON object string of environment variables to set'
    required: false
    default: '{}'
runs:
  using: "composite"
  steps:
    - uses: fizyk/actions-reuse/.github/actions/uv-setup@v5.2.0
      with:
        python-version: ${{ inputs.python-version }}
        uv-install-options: ${{ inputs.uv-install-options }}
        cache: ${{ inputs.cache }}
    - uses: fizyk/actions-reuse/.github/actions/uv-run@v5.2.0
      with:
        command: ${{ inputs.command }}
        env: ${{ inputs.env }}
