name: 'Setup uv environment'
description: 'Setup uv'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  uv-install-options:
    description: "uv sync options"
    default: ""
  cache:
    description: "Cache python environment?"
    default: true
runs:
  using: "composite"
  steps:
    - id: preserve-envvars
      shell: bash
      run: echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> "$GITHUB_OUTPUT"
    - name: Set up uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: ${{ inputs.cache }}
    - shell: bash
      if: steps.preserve-envvars.outputs.PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${{ steps.preserve-envvars.outputs.PKG_CONFIG_PATH }}" >> "$GITHUB_ENV"
    - name: Install Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: uv sync --all-groups ${{ inputs.uv-install-options }}
