name: 'Pipenv run'
description: 'Run tests'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  command:
    description: 'Command to run'
    required: true
  fetch-depth:
    description: 'How deep to fetch commits'
    default: 1
  pipenv-install-options:
    description: "Pipenv install options"
    default: ""
  cache:
    description: "Cache python environment?"
    default: true
runs:
  using: "composite"
  steps:
    - uses: fizyk/actions-reuse/.github/actions/pipenv-setup@v3.1.1
      with:
        python-version: ${{ inputs.python-version }}
        fetch-depth: ${{ inputs.fetch-depth }}
        pipenv-install-options: ${{ inputs.pipenv-install-options }}
        cache: ${{ inputs.cache }}
    - uses: fizyk/actions-reuse/.github/actions/pipenv-run@v3.1.1
      with:
        command: ${{ inputs.command }}
