name: 'Pipenv run'
description: 'Run tests'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  allow-prereleases:
    description: "Allow falling back to pre-release versions of Python when a matching GA version of Python is not available."
    required: true
  command:
    description: 'Command to run'
    required: true
  pipenv-install-options:
    description: "Pipenv install options"
    default: ""
  cache:
    description: "Cache python environment?"
    default: true
  env:
    description: 'JSON object string of environment variables to set'
    required: false
    default: '{}'
  editable:
    description: "Install package as editable?"
    default: false
runs:
  using: "composite"
  steps:
    - uses: fizyk/actions-reuse/.github/actions/pipenv-setup@v4.4.0
      with:
        python-version: ${{ inputs.python-version }}
        allow-prereleases: ${{ inputs.allow-prereleases }}
        pipenv-install-options: ${{ inputs.pipenv-install-options }}
        cache: ${{ inputs.cache }}
        editable: ${{ inputs.editable }}
    - uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.0
      with:
        command: ${{ inputs.command }}
        env: ${{ inputs.env }}
