name: 'Pipenv run'
description: 'Run tests'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  command:
    description: 'Command to run'
    required: true
  fetch-depth:
    description: 'How deep to fetch commits'
    default: 1
  pipenv-install-options:
    description: "Pipenv install options"
    default: ""
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: ${{ inputs.fetch-depth }}
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  - name: Install pipenv and dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip pipenv
      pipenv --python $(which python)
      pipenv run python --version
      pipenv install --dev ${{ inputs.pipenv-install-options }}
  - name: Run ${{ inputs.command }}
    shell: bash
    run:  pipenv run ${{ inputs.command }}
