name: 'Pipenv run'
description: 'Run command in pipenv'
inputs:
  command:
    description: 'Command to run'
    required: true
  env:
    description: 'JSON object string of environment variables to set'
    required: false
    default: '{}'
runs:
  using: "composite"
  steps:
    - name: Run ${{ inputs.command }}
      shell: bash
      run: pipenv run ${{ inputs.command }}
      env: ${{ fromJSON(inputs.env) }}
