name: Merge me test dependencies!

on:
  workflow_call:
    secrets:
      app_id:
        description: "Github Application ID that'll be used for merging"
        required: true
      private_key:
        description: "Github Application's private key"
        required: true

jobs:
  merge-me:
    name: Merge me!
    # It is often a desired behavior to merge only when a workflow execution
    # succeeds. This can be changed as needed.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Impersonate update bot
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}
      - name: Merge me!
        uses: ridedott/merge-me-action@v2.10.75
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          MERGE_METHOD: MERGE
          PRESET: DEPENDABOT_MINOR
          ENABLED_FOR_MANUAL_CHANGES: 'true'
