name: Merge me test dependencies!

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Run test commands'


jobs:
  automerge:
    uses: ./.github/workflows/shared-automerge.yml
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
