name: Run linters

on:
  workflow_call:
    inputs:
      pipenv:
        description: 'Use pipenv'
        default: false
        required: false
        type: boolean
      requirements:
        description: 'Requirements file name'
        default: 'requirements-lint.txt'
        required: false
        type: string
      python-version:
        default: "3.11"
        required: false
        type: string
      pydocstyle:
        description: 'Flag to run pydocstyle on code or not'
        type: boolean
        required: false
        default: true
      pycodestyle:
        description: 'Flag to run pycodestyle on code or not'
        type: boolean
        required: false
        default: true
      black:
        description: 'Flag to run black on code or not'
        type: boolean
        required: false
        default: true
      mypy:
        description: 'Flag to run mypy on code or not'
        type: boolean
        required: false
        default: false
      pylint:
        description: 'Flag to run pylint on code or not'
        type: boolean
        required: false
        default: false
      rst:
        description: 'Flag to run rst on code or not'
        type: boolean
        required: false
        default: false

jobs:
  pydocstyle:
    if: ${{ inputs.pydocstyle }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: fizyk/actions-reuse/.github/actions/pip@v1.3.2
      if: ${{ inputs.pipenv == false }}
      with:
        python-version: ${{ inputs.python-version }}
        requirements: ${{ inputs.requirements }}
        command: pydocstyle src/ tests/
    - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.3.2
      if: ${{ inputs.pipenv == true }}
      with:
        python-version: ${{ inputs.python-version }}
        command: pydocstyle src/ tests/

  pycodestyle:
    if: ${{ inputs.pycodestyle }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: fizyk/actions-reuse/.github/actions/pip@v1.3.2
      if: ${{ inputs.pipenv == false }}
      with:
        python-version: ${{ inputs.python-version }}
        requirements: ${{ inputs.requirements }}
        command: pycodestyle src/ tests/
    - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.3.2
      if: ${{ inputs.pipenv == true }}
      with:
        python-version: ${{ inputs.python-version }}
        command: pycodestyle src/ tests/

  black:
    if: ${{ inputs.black }}
    runs-on: ubuntu-latest
    steps:
    - uses: fizyk/actions-reuse/.github/actions/pip@v1.3.2
      if: ${{ inputs.pipenv == false }}
      with:
        python-version: ${{ inputs.python-version }}
        requirements: ${{ inputs.requirements }}
        command: black --diff --check src/ tests/
    - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.3.2
      if: ${{ inputs.pipenv == true }}
      with:
        python-version: ${{ inputs.python-version }}
        command: black --diff --check src/ tests/

  mypy:
    if: ${{ inputs.mypy }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: fizyk/actions-reuse/.github/actions/pip@v1.3.2
        if: ${{ inputs.pipenv == false }}
        with:
          python-version: ${{ inputs.python-version }}
          requirements: ${{ inputs.requirements }}
          command: mypy src/ tests/
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.3.2
        if: ${{ inputs.pipenv == true }}
        with:
          python-version: ${{ inputs.python-version }}
          command: mypy src/ tests/


  pylint:
    if: ${{ inputs.pylint }}
    runs-on: ubuntu-latest
    steps:
      - uses: fizyk/actions-reuse/.github/actions/pip@v1.3.2
        if: ${{ inputs.pipenv == false }}
        with:
          python-version: ${{ inputs.python-version }}
          requirements: ${{ inputs.requirements }}
          command: pylint src/ tests
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.3.2
        if: ${{ inputs.pipenv == true }}
        with:
          python-version: ${{ inputs.python-version }}
          command: pylint src/ tests

  rst:
    if: ${{ inputs.rst }}
    runs-on: ubuntu-latest
    steps:
      - uses: fizyk/actions-reuse/.github/actions/pip@v1.3.2
        if: ${{ inputs.pipenv == false }}
        with:
          python-version: ${{ inputs.python-version }}
          requirements: ${{ inputs.requirements }}
          command: rst-lint *.rst
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.3.2
        if: ${{ inputs.pipenv == true }}
        with:
          python-version: ${{ inputs.python-version }}
          command: rst-lint *.rst
