name: Run linters

on:
  workflow_call:
    inputs:
      requirements:
        description: 'Requirements file name'
        default: 'requirements-lint.txt'
        required: false
        type: string
      python-version:
        default: "3.10"
        required: false
        type: string
      mypy:
        description: 'Flag to run mypy on code or not'
        type: boolean
        required: false
        default: false
      pylint:
        description: 'Flag to run pylint on code or not'
        type: boolean
        required: false
        default: false

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run pydocstyle
      run: |
        pydocstyle src/ tests/

  pycodestyle:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run pydocstyle
      run: |
        pycodestyle src/ tests/
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@21.7b0

  mypy:
    if: ${{ inputs.mypy }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run Mypy type checks
      run: |
        mypy src/ tests/
  pylint:
    if: ${{ inputs.pylint }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run pylint
      run: |
        pylint src/ tests
