name: Run linters

on:
  workflow_call:
    inputs:
      requirements:
        description: 'Requirements file name'
        default: 'requirements-lint.txt'
        required: false
        type: string
      python-version:
        default: "3.11"
        required: false
        type: string
      pydocstyle:
        description: 'Flag to run pydocstyle on code or not'
        type: boolean
        required: false
        default: true
      pycodestyle:
        description: 'Flag to run pycodestyle on code or not'
        type: boolean
        required: false
        default: true
      black:
        description: 'Flag to run black on code or not'
        type: boolean
        required: false
        default: true
      mypy:
        description: 'Flag to run mypy on code or not'
        type: boolean
        required: false
        default: false
      pylint:
        description: 'Flag to run pylint on code or not'
        type: boolean
        required: false
        default: false
      rst:
        description: 'Flag to run rst on code or not'
        type: boolean
        required: false
        default: false

jobs:
  pydocstyle:
    if: ${{ inputs.pydocstyle }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run pydocstyle
      run: |
        pydocstyle src/ tests/

  pycodestyle:
    if: ${{ inputs.pycodestyle }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run pydocstyle
      run: |
        pycodestyle src/ tests/
  black:
    if: ${{ inputs.black }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run black
      run: |
        black --diff --check src/ tests/

  mypy:
    if: ${{ inputs.mypy }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run Mypy type checks
      run: |
        mypy src/ tests/
  pylint:
    if: ${{ inputs.pylint }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run pylint
      run: |
        pylint src/ tests
  rst:
    if: ${{ inputs.rst }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run rst-lint
      run: |
        rst-lint *.rst
