name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@v3.0.1
    secrets:
      app_id: ${{ secrets.APP_ID }}
      private_key: ${{ secrets.APP_PRIVATE_KEY }}
