name: Run test commands

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  pr-check:
    uses: fizyk/actions-reuse/.github/workflows/shared-pr-check.yml@v5.4.1
    with:
      dependency-manager: 'uv'
