name: Run test commands

on:
  pull_request:
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/pipenv
        with:
          python-version: "3.13"
          command: tbump --dry-run --only-patch $(pipenv run tbump current-version)"-x"
  towncrier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/pipenv
        if: ${{ !contains(fromJSON('["dependabot[bot]","pre-commit-ci[bot]"]'), github.actor) }}
        with:
          python-version: "3.13"
          command: towncrier check --compare-with origin/main
          fetch-depth: 0
