name: Run test commands

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  pr-check:
    uses: ./.github/workflows/shared-pr-check.yml
    with:
      dependency-manager: 'uv'
