name: Run linters

on:
  workflow_call:
    inputs:
      python-version:
        default: "3.14"
        required: false
        type: string

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install pre-commit
        id: pre-commit
        run: uv tool install pre-commit && pre-commit install
      - name: Run pre-commit
        id: pre-commit-run
        run: pre-commit run --hook-stage manual --all-files
