name: Build Python 🐍 distributions 📦 and publish to PyPI

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to publish Python 🐍 distributions 📦 to PyPI'
        required: false
        default: false
        type: boolean
      artifact:
        description: 'Whether to store Python 🐍 distributions 📦 as pipeline artifact'
        required: false
        default: false
        type: boolean
      python-version:
        default: "3.14"
        required: false
        type: string
      dependency-manager:
        description: 'Build tool to use (build, uv)'
        default: 'build'
        required: false
        type: string
    secrets:
      pypi_token:
        description: 'Token used to authenticate to the PyPI'
        required: false



jobs:
  build:
    name: Build Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: fizyk/actions-reuse/.github/actions/python-build@v5.1.2
        if: ${{ inputs.dependency-manager != 'uv' }}
        with:
          python-version: ${{ inputs.python-version }}
      - uses: fizyk/actions-reuse/.github/actions/uv-build@v5.1.2
        if: ${{ inputs.dependency-manager == 'uv' }}
        with:
          python-version: ${{ inputs.python-version }}
      - name: Store distributions 📦 as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package
          path: dist/
      - name: Publish distribution 📦 to PyPI
        if: ${{ inputs.publish }}
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          password: ${{ secrets.pypi_token }}
          verbose: true
