name: Run test commands

on:
  workflow_call:
    inputs:
      python-version:
        default: "3.14"
        required: false
        type: string
      dependency-manager:
        description: 'Dependency manager to use (pipenv, uv)'
        default: 'pipenv'
        required: false
        type: string

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: fizyk/actions-reuse/.github/actions/uv@v5.2.1
        if: ${{ inputs.dependency-manager == 'uv' }}
        with:
          python-version: ${{ inputs.python-version }}
          command: tbump --dry-run --only-patch $(uv run tbump current-version)"-x"
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v5.2.1
        if: ${{ inputs.dependency-manager != 'uv' }}
        with:
          python-version: ${{ inputs.python-version }}
          allow-prereleases: false
          command: tbump --dry-run --only-patch $(pipenv run tbump current-version)"-x"
  towncrier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: fizyk/actions-reuse/.github/actions/uv@v5.2.1
        if: ${{ inputs.dependency-manager == 'uv' && !contains(fromJSON('["dependabot[bot]","pre-commit-ci[bot]"]'), github.actor) }}
        with:
          python-version: ${{ inputs.python-version }}
          command: towncrier check --compare-with origin/${{ github.base_ref }}
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v5.2.1
        if: ${{ inputs.dependency-manager != 'uv' && !contains(fromJSON('["dependabot[bot]","pre-commit-ci[bot]"]'), github.actor) }}
        with:
          python-version: ${{ inputs.python-version }}
          allow-prereleases: false
          command: towncrier check --compare-with origin/${{ github.base_ref }}
