name: Release
on:
  workflow_call:
    inputs:
      version:
        description: 'New version to be added'
        required: true
        type: string
      dependency-manager:
        description: 'Dependency manager to use (pipenv, uv)'
        default: 'pipenv'
        required: false
        type: string
    secrets:
      app_id:
        description: "Github Application ID that'll be used for releasing"
        required: true
      private_key:
        description: "Github Application's private key"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Impersonate update bot
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.private_key }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
          token: ${{ steps.app-token.outputs.token }}
      - uses: fizyk/actions-reuse/.github/actions/uv@v5.2.5
        if: ${{ inputs.dependency-manager == 'uv' }}
        with:
          python-version: "3.14"
          cache: true
          command: tbump ${{ inputs.version }} --non-interactive
      - uses: fizyk/actions-reuse/.github/actions/pipenv@v5.2.5
        if: ${{ inputs.dependency-manager != 'uv' }}
        with:
          python-version: "3.14"
          allow-prereleases: false
          cache: true
          command: tbump ${{ inputs.version }} --non-interactive
