name: Build Python 🐍 distributions 📦 and publish to PyPI

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to publish Python 🐍 distributions 📦 to PyPI'
        required: false
        default: false
        type: boolean
      artifact:
        description: 'Whether to store Python 🐍 distributions 📦 as pipeline artifact'
        required: false
        default: false
        type: boolean
      python-version:
        default: "3.14"
        required: false
        type: string
      dependency-manager:
        description: 'Build tool to use (build, uv)'
        default: 'build'
        required: false
        type: string
    secrets:
      pypi_token:
        description: 'Token used to authenticate to the PyPI'
        required: false



jobs:
  build:
    name: Build Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: fizyk/actions-reuse/.github/actions/python-build@v5.0.0
        if: ${{ inputs.dependency-manager != 'uv' }}
        with:
          python-version: ${{ inputs.python-version }}
      - uses: fizyk/actions-reuse/.github/actions/uv-build@v5.0.0
        if: ${{ inputs.dependency-manager == 'uv' }}
        with:
          python-version: ${{ inputs.python-version }}
      - name: Store distributions 📦 as artifact
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: dist/
      - name: Publish distribution 📦 to PyPI
        if: ${{ inputs.publish }}
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          password: ${{ secrets.pypi_token }}
          verbose: true
