name: Run test commands

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/pipenv
        with:
          python-version: "3.11"
          command: tbump --dry-run --only-patch $(pipenv run tbump current-version)"-x"