name: Run pytest tests

on:
  workflow_call:
    inputs:
      requirements:
        description: 'Requirements file name'
        default: 'requirements-test.txt'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements }}
    - name: Run test
      run: |
        pytest -v --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
