name: Run pytest tests

on:
  workflow_call:
    inputs:
      pipenv:
        description: 'Use pipenv'
        default: false
        required: false
        type: boolean
      requirements:
        description: 'Requirements file name'
        default: 'requirements-test.txt'
        required: false
        type: string
      test_path:
        description: 'Test path'
        default: 'tests/'
        required: false
        type: string
      pytest_opts:
        description: 'Additional pytest options'
        default: ''
        required: false
        type: string
      cover_package:
        description: 'Package to run coverage for (except for tests directory)'
        required: true
        type: string
      python-versions:
        description: 'Supported python versions'
        default: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
        required: false
        type: string
      os:
        description: 'Operating system to run tests on'
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  pytests:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: fizyk/actions-reuse/.github/actions/pip@v1.4.0
      if: ${{ inputs.pipenv == false }}
      with:
        python-version: ${{ matrix.python-version }}
        requirements: ${{ inputs.requirements }}
        command: pytest -v --cov ${{ inputs.cover_package }} ${{ inputs.test_path }} --cov-report=xml ${{ inputs.pytest_opts }}
    - uses: fizyk/actions-reuse/.github/actions/pipenv@v1.4.0
      if: ${{ inputs.pipenv == true }}
      with:
        python-version: ${{ matrix.python-version }}
        command: pytest -v --cov ${{ inputs.cover_package }} ${{ inputs.test_path }} --cov-report=xml ${{ inputs.pytest_opts }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
